#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=07
set FILEDATE="11 November 1999"
set VERSION="1.1"
set TITLE='The $z$ Transform'
set SHORT_TITLE='$z$ Transform' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh

