#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=02
set FILEDATE="7 October 1999"
set VERSION="1.1"
set TITLE='Transforms of State-Space Models'
set SHORT_TITLE='Transforms' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh
