#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=04
set FILEDATE="21 October 1999"
set VERSION="1.1"
set TITLE='State Space Models from Transfer Functions'
set SHORT_TITLE='SS from TF' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh
