#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=01
set FILEDATE="30 September 1999"
set VERSION="1.1"
set TITLE='State-Space Models'
set SHORT_TITLE='' # $z would be interpreted by the shell
set RIGHT="${TITLE}"


source ../../process.tcsh


