#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=05
set FILEDATE="28 October 1999"
set VERSION="1.1"
set TITLE='Canonical Forms of State Space Models'
set SHORT_TITLE='Canonical Forms' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh

