#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=10
set FILEDATE="25 November 1999"
set VERSION="1.1"
set TITLE='Continuous System Equivalence'
set SHORT_TITLE='Continuous System Equivalence' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh
