#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=08
set FILEDATE="18 November 1999"
set VERSION="1.1"
set TITLE='Digital System Models'
set SHORT_TITLE='Digital System Models' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh
