#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=06
set FILEDATE="4 November 1999"
set VERSION="1.1"
set TITLE='Introduction to Digital Systems'
set SHORT_TITLE='Introduction' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh

