#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=03
set FILEDATE="14 October 1999"
set VERSION="1.1"
set TITLE='Time Response for State Space Models'
set SHORT_TITLE='Time Response' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh
